name: action worklow name
on: [push,pull_request]
## OR -
#on:
#  push:
#  pull_request:
#    types: [closed, assigned, opened, reopened]
jobs:
  action-name:
    runs-on: ubuntu-latest
    steps:
      -  name: List files
         run: | # for multiline add pipe
           pwd
           ls
           echo $GITHUB_SHA #commit id
           echo $GITHUB_REPOSITORY
           echo $GITHUB_WORKSPACE
           echo "${{ github.token }}"
           git clone git@github:username/reponame =>  git clone git@github:$GITHUB_REPOSITORY
           git checkout $GITHUB_SHA #current commit
      -  name: checkout
         uses: actions/checkout@v2 # this checkouts the repository in our current folder, alternative to this is git clone in run
      -  name: List files after checkout
         run: | # for multiline add pipe
           pwd
           ls