name: Sample Workflow
on: [push]
jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
#      commands
      - name: commandStep
        run: echo "for command"
        shell: bash #optional if you want to provide specific shell
#action
      - name: actionStep
        id: greet
#existing action which is public or with in your folder
        uses: actions/hello-world-javascript-action@v1
# to provide input to action
        with:
          who-to-great: Jagriti
#output example
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"